export const mockDriversData = [
  {
    id: 1,
    name: 'Ahmed Al-Mansour',
    email: 'ahmed.almansour@example.com',
    phone: '+966501234567',
    status: 'Active',
    totalTrips: 156,
    rating: 4.8,
  },
  {
    id: 2,
    name: 'Ali Raza',
    email: 'ali.raza@example.com',
    phone: '+923001234567',
    status: 'Active',
    totalTrips: 203,
    rating: 4.9,
  },
  {
    id: 3,
    name: 'Fatima Khan',
    email: 'fatima.khan@example.com',
    phone: '+923012345678',
    status: 'Active',
    totalTrips: 189,
    rating: 4.7,
  },
  {
    id: 4,
    name: 'Mohammed Al-Qahtani',
    email: 'mohammed.alqahtani@example.com',
    phone: '+966502345678',
    status: 'Active',
    totalTrips: 342,
    rating: 4.6,
  },
  {
    id: 5,
    name: 'Bilal Ahmed',
    email: 'bilal.ahmed@example.com',
    phone: '+923023456789',
    status: 'Active',
    totalTrips: 278,
    rating: 4.5,
  },
  {
    id: 6,
    name: 'Aisha Malik',
    email: 'aisha.malik@example.com',
    phone: '+923034567890',
    status: 'Active',
    totalTrips: 167,
    rating: 4.9,
  },
  {
    id: 7,
    name: 'Abdullah Al-Otaibi',
    email: 'abdullah.alotaibi@example.com',
    phone: '+966503456789',
    status: 'Inactive',
    totalTrips: 89,
    rating: 4.7,
  },
  {
    id: 8,
    name: 'Hassan Iqbal',
    email: 'hassan.iqbal@example.com',
    phone: '+923045678901',
    status: 'Active',
    totalTrips: 312,
    rating: 4.8,
  },
  {
    id: 9,
    name: 'Zainab Abbas',
    email: 'zainab.abbas@example.com',
    phone: '+923056789012',
    status: 'Active',
    totalTrips: 245,
    rating: 4.6,
  },
  {
    id: 10,
    name: 'Omar Al-Shammari',
    email: 'omar.alshammari@example.com',
    phone: '+966504567890',
    status: 'Active',
    totalTrips: 342,
    rating: 4.6,
  },
  {
    id: 11,
    name: 'Usman Chaudhry',
    email: 'usman.chaudhry@example.com',
    phone: '+923067890123',
    status: 'Active',
    totalTrips: 421,
    rating: 4.9,
  },
  {
    id: 12,
    name: 'Sara Siddiqui',
    email: 'sara.siddiqui@example.com',
    phone: '+923078901234',
    status: 'Active',
    totalTrips: 198,
    rating: 4.8,
  },
  {
    id: 13,
    name: 'Khalid Al-Ghamdi',
    email: 'khalid.alghamdi@example.com',
    phone: '+966505678901',
    status: 'Active',
    totalTrips: 178,
    rating: 4.9,
  },
  {
    id: 14,
    name: 'Hamza Farooqi',
    email: 'hamza.farooqi@example.com',
    phone: '+923089012345',
    status: 'Active',
    totalTrips: 267,
    rating: 4.7,
  },
  {
    id: 15,
    name: 'Mariam Hussain',
    email: 'mariam.hussain@example.com',
    phone: '+923090123456',
    status: 'Active',
    totalTrips: 334,
    rating: 4.8,
  },
  {
    id: 16,
    name: 'Fahad Al-Dosari',
    email: 'fahad.aldosari@example.com',
    phone: '+966506789012',
    status: 'Active',
    totalTrips: 245,
    rating: 4.5,
  },
  {
    id: 17,
    name: 'Obaid ur Rehman',
    email: 'obaid.rehman@example.com',
    phone: '+923101234567',
    status: 'Inactive',
    totalTrips: 123,
    rating: 4.3,
  },
  {
    id: 18,
    name: 'Hafsa Mirza',
    email: 'hafsa.mirza@example.com',
    phone: '+923112345678',
    status: 'Active',
    totalTrips: 289,
    rating: 4.6,
  },
  {
    id: 19,
    name: 'Sultan Al-Harbi',
    email: 'sultan.alharbi@example.com',
    phone: '+966507890123',
    status: 'Active',
    totalTrips: 312,
    rating: 4.8,
  },
  {
    id: 20,
    name: 'Tariq Mehmood',
    email: 'tariq.mehmood@example.com',
    phone: '+923123456789',
    status: 'Active',
    totalTrips: 456,
    rating: 4.9,
  },
  {
    id: 21,
    name: 'Nadia Akhtar',
    email: 'nadia.akhtar@example.com',
    phone: '+923134567890',
    status: 'Active',
    totalTrips: 234,
    rating: 4.7,
  },
  {
    id: 22,
    name: 'Nasser Al-Anazi',
    email: 'nasser.alanazi@example.com',
    phone: '+966508901234',
    status: 'Active',
    totalTrips: 267,
    rating: 4.7,
  },
  {
    id: 23,
    name: 'Imran Sheikh',
    email: 'imran.sheikh@example.com',
    phone: '+923145678901',
    status: 'Inactive',
    totalTrips: 98,
    rating: 4.2,
  },
  {
    id: 24,
    name: 'Sadia Parveen',
    email: 'sadia.parveen@example.com',
    phone: '+923156789012',
    status: 'Active',
    totalTrips: 189,
    rating: 4.5,
  },
  {
    id: 25,
    name: 'Saad Al-Malki',
    email: 'saad.almalki@example.com',
    phone: '+966509012345',
    status: 'Inactive',
    totalTrips: 145,
    rating: 4.4,
  },
  {
    id: 26,
    name: 'Kamran Ashraf',
    email: 'kamran.ashraf@example.com',
    phone: '+923167890123',
    status: 'Active',
    totalTrips: 378,
    rating: 4.8,
  },
  {
    id: 27,
    name: 'Rabia Anwar',
    email: 'rabia.anwar@example.com',
    phone: '+923178901234',
    status: 'Active',
    totalTrips: 267,
    rating: 4.9,
  },
  {
    id: 28,
    name: 'Turki Al-Zahrani',
    email: 'turki.alzahrani@example.com',
    phone: '+966510123456',
    status: 'Active',
    totalTrips: 289,
    rating: 4.6,
  },
  {
    id: 29,
    name: 'Shahid Afridi',
    email: 'shahid.afridi@example.com',
    phone: '+923189012345',
    status: 'Active',
    totalTrips: 412,
    rating: 4.7,
  },
  {
    id: 30,
    name: 'Yousef Al-Ahmad',
    email: 'yousef.alahmad@example.com',
    phone: '+966511234567',
    status: 'Active',
    totalTrips: 421,
    rating: 4.9,
  },
  {
    id: 31,
    name: 'Farhan Akhtar',
    email: 'farhan.akhtar@example.com',
    phone: '+923190123456',
    status: 'Active',
    totalTrips: 345,
    rating: 4.8,
  },
  {
    id: 32,
    name: 'Ibrahim Al-Rashid',
    email: 'ibrahim.alrashid@example.com',
    phone: '+966512345678',
    status: 'Active',
    totalTrips: 198,
    rating: 4.8,
  },
  {
    id: 33,
    name: 'Shazia Naeem',
    email: 'shazia.naeem@example.com',
    phone: '+923201234567',
    status: 'Active',
    totalTrips: 223,
    rating: 4.6,
  },
  {
    id: 34,
    name: 'Hamad Al-Juhani',
    email: 'hamad.aljuhani@example.com',
    phone: '+966513456789',
    status: 'Inactive',
    totalTrips: 76,
    rating: 4.2,
  },
  {
    id: 35,
    name: 'Salman Butt',
    email: 'salman.butt@example.com',
    phone: '+923212345678',
    status: 'Active',
    totalTrips: 389,
    rating: 4.7,
  },
  {
    id: 36,
    name: 'Mansour Al-Sulami',
    email: 'mansour.alsulami@example.com',
    phone: '+966514567890',
    status: 'Active',
    totalTrips: 334,
    rating: 4.7,
  },
  {
    id: 37,
    name: 'Nawaz Sharif',
    email: 'nawaz.sharif@example.com',
    phone: '+923223456789',
    status: 'Active',
    totalTrips: 467,
    rating: 4.9,
  },
  {
    id: 38,
    name: 'Nawaf Al-Buqami',
    email: 'nawaf.albuqami@example.com',
    phone: '+966515678901',
    status: 'Active',
    totalTrips: 423,
    rating: 4.9,
  },
  {
    id: 39,
    name: 'Asma Chaudhry',
    email: 'asma.chaudhry@example.com',
    phone: '+923234567890',
    status: 'Active',
    totalTrips: 278,
    rating: 4.8,
  },
  {
    id: 40,
    name: 'Faisal Al-Qarni',
    email: 'faisal.alqarni@example.com',
    phone: '+966516789012',
    status: 'Active',
    totalTrips: 356,
    rating: 4.6,
  },
];

export const mockClientsData = [
  {
    id: 1,
    name: 'Saudi Telecom Company',
    email: 'contact@stc.com.sa',
    phone: '+966501111111',
    status: 'Active',
    type: 'Enterprise',
    services: ['Seo', 'UI/UX Design', 'Web Development', 'Consulting'],
  },
  {
    id: 2,
    name: 'Al-Noor Group',
    email: 'info@alnoor.com',
    phone: '+966502222222',
    status: 'Active',
    type: 'Premium',
    services: ['Seo', 'UI/UX Design', 'Web Development'],
  },
  {
    id: 3,
    name: 'Gulf Express Logistics',
    email: 'support@gulfexpress.com',
    phone: '+966503333333',
    status: 'Active',
    type: 'Standard',
    services: ['Seo', 'Web Development'],
  },
  {
    id: 4,
    name: 'Desert Delivery Services',
    email: 'hello@desertdelivery.com',
    phone: '+966504444444',
    status: 'Inactive',
    type: 'Standard',
    services: ['Seo', 'Consulting'],
  },
  {
    id: 5,
    name: 'Speed Transport',
    email: 'admin@speedtransport.com',
    phone: '+966505555555',
    status: 'Active',
    type: 'Premium',
    services: ['UI/UX Design', 'Web Development', 'Consulting'],
  },
  {
    id: 6,
    name: 'Quick Dispatch Co',
    email: 'ops@quickdispatch.com',
    phone: '+966506666666',
    status: 'Active',
    type: 'Enterprise',
    services: ['Seo', 'UI/UX Design', 'Consulting'],
  },
  {
    id: 7,
    name: 'Route Masters',
    email: 'info@routemasters.com',
    phone: '+966507777777',
    status: 'Active',
    type: 'Standard',
    services: ['Web Development'],
  },
  {
    id: 8,
    name: 'Swift Logistics',
    email: 'contact@swiftlog.com',
    phone: '+966508888888',
    status: 'Active',
    type: 'Premium',
    services: ['Seo', 'UI/UX Design', 'Consulting'],
  },
  {
    id: 9,
    name: 'Engro Corporation',
    email: 'info@engro.com.pk',
    phone: '+923011111111',
    status: 'Active',
    type: 'Enterprise',
    services: ['Seo', 'UI/UX Design', 'Web Development', 'Consulting'],
  },
  {
    id: 10,
    name: 'Nestle Pakistan',
    email: 'contact@nestle.pk',
    phone: '+923022222222',
    status: 'Active',
    type: 'Premium',
    services: ['Seo', 'Consulting'],
  },
  {
    id: 11,
    name: 'K-Electric',
    email: 'support@ke.com.pk',
    phone: '+923033333333',
    status: 'Active',
    type: 'Enterprise',
    services: ['Web Development', 'UI/UX Design'],
  },
  {
    id: 12,
    name: 'PTCL',
    email: 'info@ptcl.com.pk',
    phone: '+923044444444',
    status: 'Active',
    type: 'Enterprise',
    services: ['Seo', 'Consulting'],
  },
];

export const mockStats = {
  totalTrips: 1247,
  totalDistance: 45320,
  totalEarnings: 125400,
  avgRating: 4.7,
  activeDrivers: 54,
  completedDeliveries: 1895,
  averageDeliveryTime: '32 mins',
};

export const generateMockStats = (startDate, endDate) => {
  const days = Math.max(
    1,
    Math.ceil((new Date(endDate) - new Date(startDate)) / (1000 * 60 * 60 * 24))
  );

  return {
    totalTrips: Math.floor(Math.random() * 500 + 400 * days),
    totalDistance: Math.floor(Math.random() * 5000 + 3000 * days),
    totalEarnings: Math.floor(Math.random() * 50000 + 30000 * days),
    avgRating: (Math.random() * 0.5 + 4.4).toFixed(1),
    activeDrivers: Math.floor(Math.random() * 15 + 45),
    completedDeliveries: Math.floor(Math.random() * 300 + 250 * days),
    averageDeliveryTime: Math.floor(Math.random() * 15 + 25) + ' mins',
  };
};